  version: "3"
  services:
    cinemastorage:
      image: postgres:9.6
      container_name: cinemastorage
      ports:
        - 5432:15432
      env_file:
        - .db.env
    application:
      container_name: cinema
      image: cinema_app
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
         - 8080:8080
      env_file:
        - .app.env
      restart: on-failure
      depends_on:
         - cinemastorage